spring:
  datasource:
    url: jdbc:mysql://106.13.104.180:3306/study_system?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: "!QAZxsw2"
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true